version: "3.7"
services:
  app:
    build: .
    image: quizmaster
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - ./conf/quiz:/src/dist/server-1.0/conf/quiz
      - ./conf/application.conf:/src/dist/server-1.0/conf/application.conf
    command: "dist/server-1.0/bin/server"
