version: "3.7"
services:
  app:
    stdin_open: true
    tty: true
    image: quizmaster
    ports:
      - "9000:9000"
    volumes:
      - ./conf/quiz:/src/dist/server-1.0/conf/quiz
    command: "dist/server-1.0/bin/server"
