title: Demo quiz
author: Jens Nyman
masterSecret: quiz # Remove this line to allow anyone to access the master controls

rounds:
  - name: Geography
    questions:
      - question: What is the capital of France?
        choices: [Paris, London, Brussels, Berlin]
        answer: Paris
        image: {src: geography/france.png, size: small}
        answerImage: {src: geography/france-answer.png, size: large}
        answerDetail: Image released under Creative Commons by Destination2 (www.destination2.co.uk)
        pointsToGain: 0
        maxTimeSeconds: 180
        onlyFirstGainsPoints: true

      - question: What is the capital of Belgium?
        choices: [Paris, London, Brussels, Berlin]
        answer: Brussels
        pointsToGainOnFirstAnswer: 1.5
        pointsToGain: 1.2
        pointsToGainOnWrongAnswer: -0.5
        maxTimeSeconds: 180

      - question: Who was the country Columbia named after?
        answer: Christoffer Columbus
        maxTimeSeconds: 180

      - question: What city does this video from 1935 show?
        choices: [Tokyo, Guatemala City, Mexico City, Salt Lake City]
        answer: Guatemala City
        videoSrc: geography/about_bananas.mp4
        maxTimeSeconds: 180

      - questionType: orderItems
        question: Order these cities from small to large
        questionDetail: Population according to Google on July 2020
        orderedItemsThatWillBePresentedInAlphabeticalOrder:
         - {item: Riga, answerDetail: ~600k}
         - {item: Stockholm, answerDetail: ~1M}
         - {item: Berlin, answerDetail: ~4M}
         - {item: London, answerDetail: ~9M}
        pointsToGain: 2
        maxTimeSeconds: 180

  - name: Music round
    questions:
      - question: After which season is this track named?
        questionDetail: (Royalty Free Music from Bensound)
        answer: Summer
        answerDetail: (By Bensound)
        audioSrc: music_round/bensound-summer.mp3
        maxTimeSeconds: 180

  - name: Double questions round
    questions:
      - questionType: double
        verbalQuestion: How many sides does a rectangle have?
        verbalAnswer: 4
        textualQuestion: How many sides does a triangle have?
        textualChoices: [3, 4, 5, 6]
        textualAnswer: 3
