!!app.models.quiz.config.ParsableQuizConfig
rounds:
  - name: Geography
    questions:
      - !!app.models.quiz.config.ParsableQuizConfig$Question$Single
        question: What is the capital of France?
        answer: Paris
        choices: [Paris, London, Brussels, Berlin]
        image: {src: geography/france.png, size: small}
        answerImage: {src: geography/france-answer.png, size: large}
        answerDetail: Image released under Creative Commons by Destination2 (www.destination2.co.uk)
        pointsToGain: 2
        maxTimeSeconds: 8
        onlyFirstGainsPoints: true

      - !!app.models.quiz.config.ParsableQuizConfig$Question$Single
        question: What is the capital of Belgium?
        answer: Brussels
        choices: [Paris, London, Brussels, Berlin]
        maxTimeSeconds: 60

      - !!app.models.quiz.config.ParsableQuizConfig$Question$Single
        question: Who was the country Columbia named after?
        answer: Christoffer Columbus
        maxTimeSeconds: 8

  - name: Music round
    questions:
      - !!app.models.quiz.config.ParsableQuizConfig$Question$Single
        question: After which season is this track named?
        answer: Summer
        answerDetail: Royalty Free Music from Bensound
        audioSrc: music_round/bensound-summer.mp3
        maxTimeSeconds: 15
